Appliscale/perun

.travis.yml, README.md, build.sh, cfcliparser/cliparser.go, cfconfiguration/cfconfiguration.go, cfcontext/cfcontext.go, cfconverter/cfconverter.go, cflogger/cflogger.go, cfofflinevalidator/cfofflinevalidator.go, cfofflinevalidator/cfvalidators/vpc.go, cfonlinevalidator/cfonlinevalidator.go, cfspecification/cfspecification.go, config.yaml, main.go
I've also changed fmt.println() to our cflogger in several places.
=> Multi-Level configuration

README.md, cfcliparser/cliparser.go, cflogger/cflogger.go, cfonlinevalidator/cfonlinevalidator.go
Adding basic MFA authentication and showing details about profile and configuration.
=> Adding MFA authentication

.gitignore, cfconfiguration/cfconfiguration.go, cfconfiguration/cffinder_unix.go, cfconfiguration/cffinder_unix_test.go
Configuration levels in precedence order:
1. User directory (~/.config)
2. Global (/etc)
3. .git root (github.com/Appliscale/cftool)
=> multi level configuration update, preparation for multi-os support

README.md, build.sh
just documentation update, to stay up-to-date with code
=> configuration documentation update

README.md, cfcliparser/cliparser.go, cfconfiguration/cfconfiguration.go, cfcontext/cfcontext.go, cfconverter/cfconverter.go, cflogger/cflogger.go, cfofflinevalidator/cfofflinevalidator.go, cfonlinevalidator/cfonlinevalidator.go, cfspecification/cfspecification.go, main.go
I'm already using PerunCloud name in comments 😃
=> Adding some comments for GoDoc

README.md
=> Add homebrew support for perun

.gitignore, Makefile, cliparser/cliparser.go, cliparser/cliparser_test.go, configuration/configuration.go, configuration/configuration_test.go, configuration/test_resources/test_config.yaml, context/context.go, defaults/main.yaml, logger/logger.go, onlinevalidator/onlinevalidator.go, utilities/utilities.go
Adding new parameters and fixing old ones for other CLI and configuration tweaks.
This closes #40.
=> Adding `--duration` flag and configuration settings.

.gitignore, cliparser/cliparser.go, cliparser/cliparser_test.go, logger/logger.go, main.go, utilities/utilities.go
=> Adding --version parameter.

offlinevalidator/offlinevalidator.go, offlinevalidator/template/template.go
https://github.com/Appliscale/perun/issues/56
=> Replaced YAML parsing library to gopkg.in/yaml.v2

.gitignore, offlinevalidator/parsers/jsonparser.go, offlinevalidator/parsers/jsonparser_test.go, offlinevalidator/parsers/test_resources/sample_template.json, offlinevalidator/template/templateWithDetails.go
* new json parser
* new structure for template with details regarding original file
offset
=> Validation - Improvements #37

DEPENDENCIES.md, README.md, cliparser/cliparser.go, cliparser/cliparser_test.go, configuration/configuration_test.go, context/context.go, context/context_test.go, main.go, utilities/utilities.go
Added better support for modes and command line arguments
=> Command Line Arguments Improvement #39

.gitignore, logger/logger.go, offlinevalidator/offlinevalidator.go, offlinevalidator/offlinevalidator_test.go, offlinevalidator/test_resources/test_specification.json, offlinevalidator/validators/vpc.go, offlinevalidator/validators/vpc_test.go, specification/specification.go
=> 54 Nested properties validation

cliparser/cliparser.go, converter/converter.go
Added `pretty-print` in new cliparser.
=> Pretty print in cliparser

intrinsicsolver/fixFunctions.go
=> fixed converter

.gitignore, cliparser/cliparser.go, cliparser/cliparser_test.go, converter/converter.go
"Conversion - Improvements #38
Auto-detection of input file format."
=>  file format

.travis.yml
After commitina a git tag on any branch Travis will build binaries for Linux, Mac and Windows and uploads them to GitHub release as `appliscale-integrations` user.
=> Deployment to GitHub Releases

cliparser/cliparser.go, progress/progress.go, stack/stack.go
Added support for specifying mode arguments via flags.
=> Named Mode Args #84

README.md, offlinevalidator/offlinevalidator.go
We cannot _rebase_, as of course there are conflicts in the middle that will rewrite the history, we cannot _fast forward_. So instead we need to create merge commit.
=> Merging 1.2 to 2.0 branch

README.md, cliparser/cliparser.go, stack/stack.go
I added--capabilities flag to perun create-stack and fixed logging bug.
=> Add --capabilities flag to perun create-stack

README.md, cliparser/cliparser.go, main.go
I added mfa command and updated documentation.
=> Expose --mfa mode #114

helpers/formathelpers.go, offlinevalidator/template/template.go
Added validation for non-parametrised deletion policy in offline validation
This closes https://github.com/Appliscale/perun/issues/113
=> Deletion Policy String Validation

cliparser/cliparser.go, main.go, progress/parsewriter.go, progress/progress.go, stack/applyingstackpolicy.go, stack/changeset.go, stack/creatingstack.go, stack/destroyingstack.go, stack/protectionfromtermination.go, stack/stack.go, stack/updatingstack.go
Unified some session Management stuff, Added support for changeSet creation and execution, cleaned up some code
=> Change set support

awsapi/cloudformation.go, context/context.go, context/mysession.go, main.go, onlinevalidator/onlinevalidator.go, progress/progress.go, stack/applyingstackpolicy.go, stack/changeset.go, stack/creatingstack.go, stack/destroyingstack.go, stack/protectionfromtermination.go, stack/updatingstack.go
Simplified session management process and extracted all aws api requests to interface placed in context
=> AWS Services Proxy

configuration/configuration.go, configurator/configurator.go, defaults/main.yaml, logger/logger.go, mysession/mysession.go, offlinevalidator/offlinevalidator.go, offlinevalidator/offlinevalidator_test.go
I added support for nested templates in the offline validator and modified tests.
=> Support for Nested Templates #124

Makefile, cliparser/cliparser.go, configuration/linter_configuration.go, defaults/style.yaml, linter/lint_configuration.go, linter/stylechecker.go, main.go
This closes https://github.com/Appliscale/perun/issues/9
=> Basic styling guidelines

README.md
Updated readme with current validation modes
=> Validation readme update

cliparser/cliparser.go, main.go, stack/changeset.go, stack/creatingstack.go, stack/destroyingstack.go, stack/updatingstack.go
Added auto validation when creating/updating stacks
=> Validation on Stack creation

stack/creatingstack.go, stack/destroyingstack.go, stack/updatingstack.go
Change placement of info logging about request success for stack creation/update/deletion
=> Request info replacement

parameters/parameters.go
Fixed parameters validation and added better user message
=> Parameters validation Fix

awsapi/cloudformation.go, cliparser/cliparser.go, main.go, stack/changeset.go, stack/mocks/mock_aws_api.go
Added mode for Change Set deletion
=> Delete Change Set #153

README.md, cliparser/cliparser.go
A template is no longer a required argument.
=> Setting Stack Policy with a flag #152

release.sh
I removed downloading _main.yaml_ from _release.sh_.
=> Remowing main.yaml from release.sh

linter/stylechecker.go, progress/parsewriter.go, stack/mocks/mock_context.go, utilities/utilities.go
=> Configuration file test

release.sh
The script is here: https://github.com/Appliscale/perun-dpkg/blob/master/control.sh
=> DPKG - updating perun's version

checkingrequiredfiles/creatingfiles.go, checkingrequiredfiles/creatingfiles_test.go, checkingrequiredfiles/mocks/mock_logger.go, intrinsicsolver/fixFunctions.go, logger/logger.go, main.go, validator/localvalidator.go, validator/validators/generalvalidator.go
this closes https://github.com/Appliscale/perun/issues/169
=> General rules validation mechanism

checkingrequiredfiles/creatingfiles_test.go
=> Hackaton update test fix
